neuro/Generator/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db
from neuro.modules import UserLink, Links
import pandas as pd


import random 

Generator = Blueprint('Generator',__name__)

@Generator.route('/gen', methods=['GET','POST'])
def gen():
    rand = int(random.randrange(1,100))
    link1 =Links.query.get(rand)
    return render_template('generator.html',link1=link1) 
    

neuro/Link/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db
from neuro.modules import UserLink

Link = Blueprint('Link',__name__)

@Link.route('/links2881',methods=['GET','POST'])
def links():
    
    users = UserLink.query.all()

    return render_template('links.html',users=users)
@Link.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

neuro/LinkConverterBasic/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db
from neuro.modules import UserLink

LinkConvBasic = Blueprint('LinkConvBasic',__name__)

@LinkConvBasic.route('/<short_url>')
def redirect_to_url(short_url):
    link = UserLink.query.filter_by(short_url=short_url).first_or_404()
    return redirect(link.original_url) 


@LinkConvBasic.route('/add_link', methods=['POST'])
def add_link():
    error=None
    link=UserLink.query.count()+1000
   
    original_url = request.form['original_url']
    if original_url=="":
        error="To wklejasz czy co robisz? We się nie wygłupiaj tylko konwertuj mordo"
        return render_template('main.html',error=error,link=link)
    else:    
        link = UserLink(original_url=original_url)
        db.session.add(link)
        db.session.commit()

    return render_template('link_added.html',new_link=link.short_url,original_url=link.original_url,error=error)

@LinkConvBasic.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

neuro/Main/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db
from neuro.modules import UserLink

Main = Blueprint('Main',__name__)


@Main.route('/')
def index():
    error=None
       
    link=UserLink.query.count()+1482
    
    return render_template('main.html',link=link,error=error) 


@Main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

neuro/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os


app = Flask(__name__)


app.config['SECRET_KEY']='adsadsd3123kjhg32131iplksa'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
db = SQLAlchemy(app)


from neuro.LinkConverterBasic.routes import LinkConvBasic
from neuro.Main.routes import Main
from neuro.Generator.routes import Generator
from neuro.Link.routes import Link

app.register_blueprint(Link)
app.register_blueprint(LinkConvBasic)
app.register_blueprint(Main)
app.register_blueprint(Generator)

neuro/templates/generator.html
{% extends "main.html" %}
{% block content %}

  <section class="section has-text-centered" style="background-color: coral;">
    <div class="container" >
            <div class="field">
                    <label class="label"style="font-size:7vh">Link</label>
                    <div class="control"></div>
                      <a href="{{ link1.links}}" class="title are-medium" style="color: blue; font-size: 2vh;">{{ link1.links}}</a>
                    
                    </div>
                    
                    <a href="/"><button class="button is-black" style="margin-bottom: 10vh;">Powrót do strony głównej</button></a>
            </div>
    </div>
  </section>


{% endblock content %}

neuro/templates/link_added.html
{% extends "main.html" %}
{% block content %}

  <section class="section has-text-centered" style="background-color: coral;">
    <div class="container">
            <div class="field">
                <label class="label">Twój link </label>
                <div class="control">
                    <input class="input has-text-centered" type="text" name="original_url" value="{{ original_url }}"style="margin-top: 10px;">
                </div>
            </div>
            <div class="field">
                    <label class="label">Specjalny link XD </label>
                    <div class="control">
                        <input class="input has-text-centered" id="linker" type="text" name="original_url" value="{{ url_for('LinkConvBasic.redirect_to_url', short_url=new_link, _external=True) }}" style="margin-top: 10px;">
                    </div>
                    <a href="/"><button class="button is-black" style="margin-top: 10vh;">Powrót do strony głównej</button></a>
            </div>
    </div>
  </section>


{% endblock content %}

neuro/templates/links.html
{% extends "main.html"%}
{% block content %}

<table class="table">
    <thead>
      <tr>
        <th><abbr title="Position">Numer</abbr></th>
        <th>Adresy URL</th>
        <th><abbr title="Played">Skrócone adresy URL</abbr></th>
        <th><abbr title="Won">Ilość wejść </abbr></th>
       
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th><abbr title="Position">Numer</abbr></th>
        <th>Adresy URL</th>
        <th><abbr title="Played">Skrócone adresy URL</abbr></th>
        <th><abbr title="Won">Ilość wejść </abbr></th>
        
      </tr>
    </tfoot>
    <tbody>
       {% for linkers in users %}
      <tr>
        <th>{{linkers.id}}</th>
      
        <td><a href="{{linkers.original_url}}">{{linkers.original_url}}</a></td>
        
       
        <td><a href="{{linkers.short_url}}">{{linkers.short_url}}</a></td>
        <
      </tr> 
      {%endfor%}
      
    </tbody>
  </table>

{%endblock content%}

neuro/templates/main.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dla kolegi ;)</title>
    <link rel="stylesheet" href ="{{url_for('static', filename='css/bulma.css')}}">
    
    <script type="text/javascript" src="//www.termsfeed.com/public/cookie-consent/3.1.0/cookie-consent.js"></script>
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function () {
      cookieconsent.run({"notice_banner_type":"interstitial","consent_type":"express","palette":"dark","language":"pl"});
      });
      </script>
      
      <noscript>Cookie Consent by <a href="https://www.TermsFeed.com/" rel="nofollow noopener">TermsFeed</a></noscript>
      <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static',filename='favicon/apple-touch-icon.png')}}">
      <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='favicon/favicon-32x32.png')}}">
      <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='favicon/favicon-16x16.png')}}">
      <link rel="manifest" href="{{url_for('static',filename='favicon/site.webmanifest')}}">
      <link rel="mask-icon" href="{{url_for('static',filename='favicon/safari-pinned-tab.svg')}}" color="#ffa31a">
      <meta name="msapplication-TileColor" content="#da532c">
      <meta name="theme-color" content="#ffffff">
      <meta name="hubtraffic-domain-validation"  content="23d7eb1de5a8435b" />
      <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-178262247-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-178262247-2');
    </script>


      <style>
        ::-webkit-scrollbar {
    height: 12px;
    width: 12px;
    background: #000;
}

::-webkit-scrollbar-thumb {
    background: #ff7f50;
    -webkit-border-radius: 1ex;
    -webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.75);
}

::-webkit-scrollbar-corner {
    background: #000;
}
      </style>

     

</head>

<body style="margin:0;padding: 0;">
  
  <section class="section has-background-black has-text-centered">
    <div class="text has-text-centered">
      <a class="text has-text-centered" href="/">
        <img src="static/zdjęcia/logo.png" width="350" height="200">
      </a>
      <section class="section has-text-centered has-background-black" name="Top Square" >
        <div id="Top Square"></div>
</section>
    </div>{%block content%}
    <div class='title has-text-centered has-text-white'>Kolega czeka, więc nie zwlekaj ;)</div> </div>
    <div class="title has-text-centered " style="color:#ff7f50">Link miesiąca</div>
    <figure class="  has-text-centered"><img src="static/zdjęcia/test.png" alt="Skrócony link" width="350" height="200" ></figure>
 
  </section>
  <section class="section has-background-black has-text-centered">
    <div class="Top Square" width="300" height="250"></div>
  </section>
    <section class="section has-text-centered has-text-black" style="background-color: coral;">
        <div class="text">
          <h1>
            Chcesz koledze wysłać link do swojego ulubionego filmu?
          </h1>
          <h2>Fejs, insta czy messenger blokuje twój link?</h2>
          <h2>Albo może twój kumpel siedzi w robocie?</h2>
          <h2>Tak czy siak, nieważne po co, ważne że chcesz sobie skrócić adres url  !!!</h2>
        </div>


        <div class="container">
            <form method="POST" action="{{ url_for('LinkConvBasic.add_link') }}">
                <div class="field">
                    <label class="label">Wklej swój SpEcJAlnY link</label>
                    <div class="control">
                        <input class="input has-text-white has-text-centered" type="text" name="original_url" placeholder="np. https://www.twojulubionylinkXD.pl/">
                    </div>

                </div>
                {%if error%}
                <p class="error">{{ error }}</p>
                {%endif%}
                <div class="control">
                    <button type="submit" class="button is-black">Skróć go hehe !</button>
                </div>
                
            </form>
           
        </div>
        <div class="text">
        <p>Wszystkie skrócone linki XD:</p>
        <p>{{link}}</p>
        </div>
    </section>
    <section class="section has-text-centered has-background-black"> 
     
      <a class="button is-info" onClick="window.location.reload();">Start!</a><br> <h2> Flappy Bird ale trochę słabe :(</h2><br><br>
      <canvas id="canvas" width="288" height="512"></canvas>
       
    </section>
    <section class="section has-text-centered has-text-black" style="background-color: coral;">
      <h2>Strona powstała w celach humorystycznych</h2>
      <h2>Każdy z nas ma kolegę, któremu jest ciągle potrzebny link do ważnych rzeczy</h2>
      <h2>Oferujemy tylko szybki, prosty skracacz linków ( czy jak to woli adresów URL XD). Dlatego korzystajcie dowoli i udostępniajcie, gdzie tylko się da XD.</h2>
      <br>
      <br>
      <h2>Pamiętaj, żeby w adresie był początek https lub http inaczej nic nie zdziałamy :(</h2>
      <br>
      <br>
      <br>{%endblock content%}
      <h2 style="color: white; text-align: center;"> Wesprzyj nas! Strona jest w pełni darmowa ale niestety serwery już nie :( Każda kwota jest mile widziana!</h2>
      <br>
      <a href="https://www.paypal.com/paypalme/dlakolegi"><button class="button is-danger" href="https://www.paypal.com/paypalme/dlakolegi" >Wesprzyj nas</button></a>
    </section>
    
   
    <footer class="footer has-text-centered has-background-black has-text-grey" style="height: 100%;">
      <div class="social">
       <a href="https://www.instagram.com/dla_kolegi/?hl=pl"style="color:coral;"><div class="insta">INSTAGRAM</div></a>
      </div>
      <div class="help">
        <p>Potrzebujesz pomocy?</p>
        <p>Coś Ci nie pasuje?</p>
        <p>Link się nie chce skrócić?</p>
        <p>U nas działa, więc nie nasz problem XD</p>
        <p>A tak serio napisz do nas na insta!</p>
        <p style="color:gray;margin-top: 5vh;">Właściele strony nie biorą odpowiedzialności za skrócone adresy url. Nie udostępniamy, promujemy czy bierzemy udział w treściach niedozwolonych. Użycie naszej usługi w celach SPAM czy w czynnościach nielegalnych jest zakazane i każde takie użycie będzie skutkowało zgłoszeniem do odpowiednich organów ścigania. Usługa jest darmowa i nie gwarantuje pełnej skuteczności.  </p>
      </div>
      
    </footer>
    <script>
      var cvs = document.getElementById("canvas");
      var ctx = cvs.getContext("2d");
      
      // load images
      
      var bird = new Image();
      var bg = new Image();
      var fg = new Image();
      var pipeNorth = new Image();
      var pipeSouth = new Image();
      
      bird.src = "static/zdjęcia/bird.png";
      bg.src = "static/zdjęcia/bg.png";
      fg.src = "static/zdjęcia/fg.png";
      pipeNorth.src = "static/zdjęcia/pipeNorth.png";
      pipeSouth.src = "static/zdjęcia/pipeSouth.png";
      
      
      // some variables
      
      var gap = 85;
      var constant;
      
      var bX = 10;
      var bY = 150;
      
      var gravity = 1.5;
      
      var score = 0;
      
      // audio files
      
      
      // on key down
      
      document.addEventListener("click",moveUp);
      
      function moveUp(){
          bY -= 25;
          
      }
      function stop(){
          by
      }
      
      // pipe coordinates
      
      var pipe = [];
      
      pipe[0] = {
          x : cvs.width,
          y : 0
      };
      
      // draw images
      
      function draw(){
          
          ctx.drawImage(bg,0,0);
          
          
          for(var i = 0; i < pipe.length; i++){
              
              constant = pipeNorth.height+gap;
              ctx.drawImage(pipeNorth,pipe[i].x,pipe[i].y);
              ctx.drawImage(pipeSouth,pipe[i].x,pipe[i].y+constant);
                   
              pipe[i].x--;
              
              if( pipe[i].x == 125 ){
                  pipe.push({
                      x : cvs.width,
                      y : Math.floor(Math.random()*pipeNorth.height)-pipeNorth.height
                  }); 
              }
      
              // detect collision
              
              if( bX + bird.width >= pipe[i].x && bX <= pipe[i].x + pipeNorth.width && (bY <= pipe[i].y + pipeNorth.height || bY+bird.height >= pipe[i].y+constant) || bY + bird.height >  cvs.height - fg.height){
                stop()
              
                 
              }
              
              if(pipe[i].x == 5){
                  score++;
                 
              }
              
              
          }
      
          ctx.drawImage(fg,0,cvs.height - fg.height);
          
          ctx.drawImage(bird,bX,bY);
          
          bY += gravity;
          
          ctx.fillStyle = "#000";
          ctx.font = "20px Verdana";
          ctx.fillText("Wynik : "+score,10,cvs.height-20);
          
          requestAnimationFrame(draw);
          
      }
      
      draw();
      
            </script>

</body>

</html>